=== jp-yuan/cs257/person.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"> 
    <xs:element name="person">
        <xs:complexType>
        <xs:sequence>
            <xs:element name="FirstName" type="xs:string"></xs:element>
            <xs:element name="LastName" type="xs:string"></xs:element>
            <xs:element name="Age">
                <xs:simpleType>
                    <xs:restriction base = "xs:integer">
                        <xs:minExclusive value="0"></xs:minExclusive>
                        <xs:maxExclusive value="100"></xs:maxExclusive>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="DOB" type="xs:date"></xs:element>
            <xs:element name="FatherName" type="xs:string"></xs:element>
            <xs:element name="MotherName" type="xs:string"></xs:element>
        </xs:sequence>
    </xs:complexType>
    </xs:element>
    
    
</xs:schema>

=== jp-yuan/cs257/tree2.xml
<?xml version="1.0" encoding="UTF-8"?>
<person xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="person.xsd" xs:schemaLocation="/Users/jianpengyuan/Desktop/untitled%20folder/person.xsd">
    <ID>287134</ID>
    <FirstName>Jack</FirstName>
    <LastName>Ma</LastName>
    <Age>31</Age>
    <DOB>1993-02-03</DOB>
    <FatherName>John Ma</FatherName>
    <MotherName>Kyle Ma</MotherName>
</person>
